export const dummyData = [
  { id: 1, name: "Anwarsha", age: 22 },
  { id: 2, name: "Bathisha", age: 52 },
  { id: 3, name: "Catherine", age: 21 },
  { id: 4, name: "Binshad", age: 20 },
  { id: 5, name: "Akhil", age: 12 },
  { id: 6, name: "Prasad", age: 34 },
  { id: 7, name: "Aswar", age: 16 },
  { id: 8, name: "Ameen", age: 13 },
  { id: 9, name: "Niyas", age: 25 },
  { id: 10, name: "Zain", age: 27 },

  { id: 11, name: "Malik", age: 32 },
  { id: 12, name: "Shamsudheen", age: 60 },
  { id: 13, name: "Abhishek", age: 28 },
  { id: 14, name: "Muhammed", age: 24 },
  { id: 15, name: "Khadeeja", age: 45 },
  { id: 16, name: "Beena", age: 44 },
  { id: 17, name: "Aseena", age: 40 },
  { id: 18, name: "Dawood", age: 36 },
  { id: 19, name: "Riyas Khan", age: 18 },
  { id: 20, name: "Ajmal", age: 17 },

  { id: 21, name: "Govardhan", age: 24 },
  { id: 22, name: "Rohith", age: 43 },
  { id: 23, name: "Gokul", age: 30 },
  { id: 24, name: "Rahul", age: 26 },
  { id: 25, name: "Sushanth", age: 38 },
];
